[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | migrations
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_first_party = ["app"]  # название твоего проекта
skip = ["migrations", "__init__.py", ".venv"]

[tool.autoflake]
check = false
remove-all-unused-imports = true
remove-unused-variables = true
ignore-init-module-imports = true
recursive = true
exclude = ["migrations", ".venv"]



# Очистка мусора
# autoflake --remove-all-unused-imports --remove-unused-variables --in-place -r app

# Сортировка импортов
# isort app

# Форматирование
# black app